// app/src/routes/timeline/Grid.svelte
<script lang="ts">
	import { ContainerConfig } from 'konva/lib/Container';
	import { Stage, Layer, Rect, Line, Text } from 'svelte-konva';
	import type { KonvaWheelEvent } from 'svelte-konva';

	export let layerWidth: number;
	export let layerHeight: number;
	export let initialStageWidth = 1200;
	export let initialStageHeight = 600;
	export let stepBaseX: number = 0;
	export let stepBaseY: number = 0;
	export let xAxis = true;
	export let yAxis = true;

    let stage: Stage;

	$: startX = layerWidth / 2; //FIXME not adapting to zoom drag
	$: startY = layerHeight / 2;
	$: console.log('startX: ' + startX);
	$: console.log('startY: ' + startY);


    let stageConfig: ContainerConfig;
    $: stageConfig = {
        draggable: true,
        offsetX: startX - initialStageWidth / 2,
        offsetY: startY - initialStageHeight / 2,
        width: initialStageWidth,
        height: initialStageHeight
    };

    $: layerConfig = {
        width: layerWidth,
        height: layerHeight
    };

    $: scaledStageWidth = (stageConfig.width ?? 0) / (stageConfig.scaleX ?? 1);
    $: scaledStageHeight = (stageConfig.height ?? 0) / (stageConfig.scaleY ?? 1);

    $: stageX = startX - scaledStageWidth / 2;
    $: stageY = startY - scaledStageWidth / 2;
	$: console.log('stageX: ' + stageX);

	$: amountX = xAxis ? Math.floor(scaledStageWidth / stepBaseX) : 0;
	$: amountY = yAxis ? Math.floor(scaledStageHeight / stepBaseY) : 0;
	$: console.log('amountX: ' + amountX);
	$: console.log('amountY: ' + amountY);

	$: gridLinesX =
		amountX > 0
			? Array.from({ length: amountX }, (_, index) => index * stepBaseX + stageX)
			: [];
	$: gridLinesY =
		amountY > 0
			? Array.from({ length: amountY }, (_, index) => index * stepBaseY + stageY)
			: [];
	$: console.log('gridLinesX: ' + gridLinesX);
	$: console.log('gridLinesY: ' + gridLinesY);

	function zoomStage(event: KonvaWheelEvent) {
		event.preventDefault();

		const detailEvent = event.detail.evt;

		let oldScale = stageConfig.scaleX ?? 1;
		let pointer = {
			x: detailEvent.pageX,
			y: detailEvent.pageY
		};

		let mouse = {
			x: (pointer.x - (stageConfig.x ?? 0)) / oldScale,
			y: (pointer.y - (stageConfig.y ?? 0)) / oldScale
		};

		let direction = detailEvent.deltaY > 0 ? -1 : 1;

		if (detailEvent.ctrlKey) {
			direction = -direction;
		}

		let newScale = direction > 0 ? oldScale * 1.1 : oldScale / 1.1;

		stageConfig.scaleX = newScale;
		stageConfig.scaleY = newScale;

		stageConfig.x = pointer.x - mouse.x * newScale;
		stageConfig.y = pointer.y - mouse.y * newScale;

		//   let visibleStepAmount = Math.floor((initialStageWidth / newScale) / stepSize);

		//   if (visibleStepAmount > 100) {
		//     stepSize *= 10;
		//   }

		//   if (visibleStepAmount < 10) {
		//     stepSize /= 10;
		//   }
	}
</script>

<div id="main">
	<div class="canvasContainer">
		<Stage bind:this={stage} on:wheel={zoomStage} bind:config={stageConfig}>
			<Layer config={layerConfig}>
				<Rect
					config={{
						x: 0,
						y: 0,
						width: layerWidth,
						height: layerWidth,
						fill: 'white'
					}}
				/>
				{#if xAxis}
					{#each gridLinesX as x}
						<Line
							config={{
								points: [x, 0, x, layerHeight],
								stroke: 'darkgrey',
								strokeWidth: 1
							}}
						/>
						<Line
							config={{
								points: [x, startY - 10, x, startY + 10],
								stroke: 'black',
								strokeWidth: 1
							}}
						/>
						<Text
							config={{
								text: x.toString(),
								x: x,
								y: startY + 10,
								fill: 'black',
								fontSize: 18,
								fontFamily: 'Calibri',
								align: 'center'
							}}
						/>
					{/each}
				{/if}
				{#if yAxis}
					{#each gridLinesY as y}
						<Line
							config={{
								points: [0, y, layerWidth, y],
								stroke: 'darkgrey',
								strokeWidth: 1
							}}
						/>
						<Line
							config={{
								points: [startX - 10, y, startX + 10, y],
								stroke: 'black',
								strokeWidth: 1
							}}
						/>
						<Text
							config={{
								text: y.toString(),
								y: y,
								x: startX - 10,
								fill: 'black',
								fontSize: 18,
								fontFamily: 'Calibri',
								align: 'center'
							}}
						/>
					{/each}
				{/if}
				<slot />
			</Layer>
		</Stage>
	</div>
</div>

<style>
	.konvajs-content {
		cursor: grab;
	}
</style>

// frontend/src/components/timeline/Grid.vue
<template>
  <v-stage ref="konva" @wheel="zoom" :config="stageConfig" :width="initialStageWidth" :height="initialStageHeight">
    <v-layer :config="layerConfig">
      <v-rect
        :config="{ x: 0, y: 0, width: props.layerSize, height: props.layerSize, fill: 'white' }"
      />
      <v-line
        v-for="x in gridLinesX"
        :key="x"
        :config="{ points: [x, 0, x, layerSize], stroke: 'darkgrey', strokeWidth: 1 }"
      />
      <v-line
        v-for="x in gridLinesX"
        :key="x"
        :config="{ points: [x, middle - 10, x, middle + 10], stroke: 'black', strokeWidth: 1 }"
      />
      <v-line
        :config="{ points: [0, middle, layerSize, middle], stroke: 'black', strokeWidth: 1 }"
      />
      <v-line
        v-for="x in gridLinesX"
        :key="x"
        :config="{ points: [x, middle - 10, x, middle + 10], stroke: 'black', strokeWidth: 1 }"
      />
      <v-text
        v-for="x in gridLinesX"
        :key="x"
        :config="{ text: x, x: x, y: middle + 10, fill: 'black', fontSize: 18,
        fontFamily: 'Calibri', align: 'center' }"
        />
      <slot></slot>
    </v-layer>
  </v-stage>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';


import Konva from 'konva';

// Props
const props = defineProps({
  layerSize: {
    type: Number,
    default: 30000,
  },
  initialStageWidth: {
    type: Number,
    default: 1200,
  },
  initialStageHeight: {
    type: Number,
    default: 600,
  },
  initialStepSize: {
    type: Number,
    default: 50,
  },
});

const middle = ref<number>(props.layerSize / 2);
const stepSize = ref<number>(props.initialStepSize)

const konva = ref<any | null>(null)
const stage = computed(() => konva.value?.getStage() as Konva.Stage | null)
// const layer = computed(() => stage.value?.getLayers()[0])



// Stage configuration
const stageConfig = {
  draggable: true,
  offsetX: middle.value - (props.initialStageWidth / 2),
  offsetY: middle.value - (props.initialStageHeight / 2)
};

// Layer configuration
const layerConfig = {
  width: props.layerSize,
  height: props.layerSize,
};

// Computed properties for grid lines
const gridLinesX = computed(() => Array.from({ length: Math.ceil(props.layerSize / stepSize.value) }, (_, index) =>
  index * stepSize.value
));

function zoom(e: {evt: WheelEvent}) {
  var scaleBy = 1.1;

  // stop default scrolling
  e.evt.preventDefault();

  let st = stage.value;
  if(!st) return

  var oldScale = st.scaleX();
  var pointer = st.getPointerPosition()!;

  var mousePointTo = {
    x: (pointer.x - st.x()) / oldScale,
    y: (pointer.y - st.y()) / oldScale,
  };

  let direction = e.evt.deltaY > 0 ? -1 : 1;

  if (e.evt.ctrlKey) {
    direction = -direction;
  }

  var newScale = direction > 0 ? oldScale * scaleBy : oldScale / scaleBy;

  st.scale({ x: newScale, y: newScale });

  var newPos = {
    x: pointer.x - mousePointTo.x * newScale,
    y: pointer.y - mousePointTo.y * newScale,
  };
  st.position(newPos);
  

  let visibleStepAmount = Math.floor((props.initialStageWidth / newScale) / stepSize.value)
  console.log("---")
  console.log(visibleStepAmount)
  console.log("---")

  if(visibleStepAmount > 100) {
    stepSize.value *= 10
  }

  if(visibleStepAmount < 10) {
    stepSize.value /= 10
  }
}
</script>

<style scoped>
  .konvajs-content {
    cursor: grab;
  }
</style>
