// app/src/routes/timeline/+page.svelte
<script lang="ts">
	import Grid from './Grid.svelte';
import Timeline from './Timeline.svelte';


	export let data;

    
    let layerSize = 30000;
    let initialStageWidth = 1200;
    let initialStageHeight = 600;
    let initialStepSize = 50;

</script>

<Grid layerWidth={layerSize} layerHeight={layerSize} {initialStageWidth} {initialStageHeight} stepBaseX={initialStepSize} yAxis={false} >
    <Timeline originX={initialStageWidth/2} originY={initialStageHeight/2} evCatPairs={data.evCatPairs}></Timeline>
</Grid>

// frontend/src/views/Timeline.vue
<script setup lang="ts">
import { ref } from "vue";
import Grid from "../components/timeline/Grid.vue";
import XmlVisualizer from "../components/timeline/XmlVisualizer.vue";


const layerSize = ref(30000);
const stageWidth = ref(1200);
const stageHeight = ref(600);
const stepSize = ref(50);


const originX = ref(layerSize.value / 2);
const originY = ref(layerSize.value / 2);
const eventHeight = ref(40);

</script>

<template>
  <Grid id="grid" :layerSize="layerSize" :initialStageWidth="stageWidth" :initialStageHeight="stageHeight" :stepSize="stepSize">
    <XmlVisualizer :originX="originX" :originY="originY" :availableHeight="stageHeight" :availableWidth="stageWidth" :eventHeight="eventHeight"/>
  </Grid>
</template>

<style scoped>
</style>
